first commit
PhilippNikitin/go-db-sql-final pull request #1
Opened 2024-08-23 16:50 UTC by PhilippNikitin

2024-08-23 19:05 UTC, dirtymew requested changes
Привет Филипп

отличная работа:
 - структура проекта
 - свои ошибки

есть что поправить см комментарии

2024-08-23 19:05 UTC, dirtymew commented on internal/constants/constants.go
> +	PathToLocalDB = "/home/nikitin/Dev/Yandex Practicum/sprint8/go-db-sql-final/tracker.db"
так не нужно делать - используй относительные пути

2024-08-23 19:05 UTC, dirtymew commented on internal/models/models.go
> +package models
отличный лайаут - очень хорошо

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +// написать тест для GetParcelCountByClient
используй комент TODO  )

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +package parcel_store
лучше выделить пакет parcel и в нем service и store - такие длинные имена допускаются но не приветствуются - говорит о том что что-то не до проектированно

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +func (s ParcelStore) GetParcelCountByClient(client int) (int, error) {
а зачем? кажется что это лишняя ручка

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +	parcelCountForClient, err := s.GetParcelCountByClient(client)
ну это мягко говоря не оптимизация - дополнительный очень дорогой запрос к БД - чтобы сэкономить на аллокации. Так не надо делать.

если хочется то можно Limit поставить в запрос

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +
нужно еще ошибку из rows обработать
http://go-database-sql.org/errors.html

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +	rows, err := s.db.Query(`SELECT *
лучше явно указать поля - чем использовать *

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +		fmt.Println(err)
лишнее логирование - в функции main ошибки печатаются уже

логирования нет к сожалению в курсе ((

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +	row := s.db.QueryRow(`SELECT status
тут тоже очень не оптимально - все можно сделать одним запросов Update

если хочется ошибку вернуть если нет запрошеного id то проверяй RowAffected

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +		return parcel_errors.ErrUnsuitableParcelStatus
если ты тут ошибку возвращаешь для этого кейса то main функцию надо поправить - она до конца не отработает

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store.go
> +	row := s.db.QueryRow(`SELECT status
тоже самое что и в SetAddress

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, models.Parcel{}, deletedParcel) // проверяем, что вернулась пустая структура Parcel
в go не принято работать с данными если есть ошибка - но если хочется  проверить то тогда require.Nil или require.Empty

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Error(t, err)                            // если мы запрашиваем из БД несуществующую посылку, должна вернуться ошибка
еще хорошо бы саму ошибку проверить assert.ErrorIs например

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, parcel, storedParcel)
assert

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, newAddress, storedParcel.Address) // проверяем, что адрес посылки изменился на предполагаемый
assert

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, testParcel, storedParcel) // проверяем, что поля посылки не изменились
assert

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +		require.Equal(t, parcelMap[parcel.Number], parcel)
assert  и тут можно лучше в testify есть функции для работы с массивами - можно обойтись без цикла и мапы тут и все проверить одним assert-ом

2024-08-23 19:05 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +func TestGetParcelCountByClient(t *testing.T) {
это лишний энпоинт

2024-08-24 14:13 UTC, PhilippNikitin commented
> Привет Филипп
> 
> отличная работа:
> 
>     * структура проекта
> 
>     * свои ошибки
> 
> 
> есть что поправить см комментарии

Привет! Огромное спасибо за ревью и обоснованные замечания) В целом, со всем согласен, осталось несколько не совсем понятных для меня моментов, если возможно, можешь пожалуйста объяснить - я под некоторыми замечаниями вопросы оставил, или намекнуть, где искать ответы. Спасибо большое!

2024-08-24 14:17 UTC, PhilippNikitin commented on internal/constants/constants.go
> +	PathToLocalDB = "/home/nikitin/Dev/Yandex Practicum/sprint8/go-db-sql-final/tracker.db"
> так не нужно делать - используй относительные пути

Почему-то не получилось использовать один краткий относительный путь наподобие "./go-db-sql-final/tracker.db" - возникала странная ошибка "unable to open database file: out of memory (14)". Пришлось написать "../../../tracker.db" (

2024-08-24 14:22 UTC, PhilippNikitin commented on internal/parcel_store/parcel_store.go
> +	parcelCountForClient, err := s.GetParcelCountByClient(client)
> ну это мягко говоря не оптимизация - дополнительный очень дорогой запрос к БД - чтобы сэкономить на аллокации. Так не надо делать.
> 
> если хочется то можно Limit поставить в запрос

Хорошо, постараюсь запомнить, что нужно избегать лишних запросов к БД. Просто подумал, что создавать пустой слайс с неизвестным количеством будущих реаллокаций из-за непонятного объема роста слайса (мы же не знаем, сколько у клиента было посылок, и сколько раз будем вызывать ф-ию append) тоже не очень эффективно, поэтому подумал, что хорошая идея создавать слайс с заранее известной capacity. Но видимо это меньшее зло в данной ситуации)

2024-08-24 14:25 UTC, PhilippNikitin commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, parcel, storedParcel)
> assert

Вот здесь не совсем понятно, почему assert. Читал, что лучше всегда по умолчанию require использовать
https://otus.ru/nest/post/1178/

2024-08-25 12:14 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, parcel, storedParcel)
нет не всегда - если require сработает то дальше тесты не будут запускаться. для одних проверок это подходит для других нет - не понятно сколько еще проверок не пройдет эта одна или еще 100500.

За статью спасибо - очень вредная. Автор явно тесты не умеет писать - по моему мнению.

2024-08-25 12:15 UTC, dirtymew commented on internal/constants/constants.go
> +	PathToLocalDB = "/home/nikitin/Dev/Yandex Practicum/sprint8/go-db-sql-final/tracker.db"
ну хотя бы

2024-08-25 12:22 UTC, dirtymew approved these changes
Привет Филипп

все супер - зачет

2024-08-25 12:22 UTC, dirtymew commented on internal/parcel/store/store.go
> +		return errors.ErrUnsuccessful
отлично @PhilippNikitin обрати внимание на main 60 строка. там дельше выполенние не пойдет - я бы поправил main

2024-08-25 12:22 UTC, dirtymew commented on internal/constants/constants.go
> +	PathToLocalDB = "/home/nikitin/Dev/Yandex Practicum/sprint8/go-db-sql-final/tracker.db"
ну вообще для тестов можно и свою бд создать и после выполнения ее удалять
посмотри на testify suite - с помощью него такое удобно делать

2024-08-25 12:22 UTC, dirtymew commented on internal/parcel/store/store_test.go
> +	assert.ElementsMatch(t, parcels, storedParcels)
отлично - тут ElementsMatch подходит

2024-08-25 12:24 UTC, dirtymew commented
> > Привет Филипп
> > отличная работа:
> > ```
> > * структура проекта
> > 
> > * свои ошибки
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > есть что поправить см комментарии
> 
> Привет! Огромное спасибо за ревью и обоснованные замечания) В целом, со всем согласен, осталось несколько не совсем понятных для меня моментов, если возможно, можешь пожалуйста объяснить - я под некоторыми замечаниями вопросы оставил, или намекнуть, где искать ответы. Спасибо большое!

@PhilippNikitin вопросов не уведел - лучше их задавать в коментах в PR

если есть что спросить то тегни меня тут - я постараюсь не пропустить в нотификацих в потоке и ответить

2024-08-25 12:26 UTC, dirtymew commented on internal/parcel_store/parcel_store_test.go
> +	require.Equal(t, parcel, storedParcel)
https://habr.com/ru/companies/joom/articles/666440/  - вот тут коротко зато по делу

2024-08-25 12:30 UTC, PhilippNikitin commented
> > > Привет Филипп
> > > отличная работа:
> > > ```
> > > * структура проекта
> > > 
> > > * свои ошибки
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > есть что поправить см комментарии
> > 
> > 
> > Привет! Огромное спасибо за ревью и обоснованные замечания) В целом, со всем согласен, осталось несколько не совсем понятных для меня моментов, если возможно, можешь пожалуйста объяснить - я под некоторыми замечаниями вопросы оставил, или намекнуть, где искать ответы. Спасибо большое!
> 
> @PhilippNikitin вопросов не уведел - лучше их задавать в коментах в PR
> 
> если есть что спросить то тегни меня тут - я постараюсь не пропустить в нотификацих в потоке и ответить

Большое спасибо за ревью. Да в целом уже все более менее понятно, вопросов не осталось) по тестам материал дополнительно поизучаю, это конечно огромный отдельный блок)

2024-08-25 12:33 UTC, PhilippNikitin commented on internal/parcel/store/store.go
> +		return errors.ErrUnsuccessful
Да-да, я уже поправил - убрал return

2024-08-25 12:35 UTC, merged